{"test_class": {"identifier": "ExceptionExtTest", "superclass": "", "interfaces": "", "fields": [], "file": "titus-common/src/test/java/com/netflix/titus/common/util/ExceptionExtTest.java"}, "test_case": {"identifier": "testToMessageChain", "parameters": "()", "modifiers": "@Test public", "return": "void", "body": "@Test\n    public void testToMessageChain() throws Exception {\n        String messageChain = ExceptionExt.toMessageChain(new RuntimeException(\"outside\", new Exception(\"inside\")));\n        assertThat(messageChain).contains(\"(RuntimeException) outside -CAUSED BY-> (Exception) inside\");\n    }", "signature": "void testToMessageChain()", "full_signature": "@Test public void testToMessageChain()", "class_method_signature": "ExceptionExtTest.testToMessageChain()", "testcase": true, "constructor": false, "invocations": ["toMessageChain", "contains", "assertThat"]}, "focal_class": {"identifier": "ExceptionExt", "superclass": "", "interfaces": "", "fields": [], "methods": [{"identifier": "silent", "parameters": "(T object, Consumer<T> invocation)", "modifiers": "public static", "return": "void", "signature": "void silent(T object, Consumer<T> invocation)", "full_signature": "public static void silent(T object, Consumer<T> invocation)", "class_method_signature": "ExceptionExt.silent(T object, Consumer<T> invocation)", "testcase": false, "constructor": false}, {"identifier": "silent", "parameters": "(RunnableWithExceptions runnable)", "modifiers": "public static", "return": "void", "signature": "void silent(RunnableWithExceptions runnable)", "full_signature": "public static void silent(RunnableWithExceptions runnable)", "class_method_signature": "ExceptionExt.silent(RunnableWithExceptions runnable)", "testcase": false, "constructor": false}, {"identifier": "doCatch", "parameters": "(Runnable action)", "modifiers": "public static", "return": "Optional<Throwable>", "signature": "Optional<Throwable> doCatch(Runnable action)", "full_signature": "public static Optional<Throwable> doCatch(Runnable action)", "class_method_signature": "ExceptionExt.doCatch(Runnable action)", "testcase": false, "constructor": false}, {"identifier": "rethrow", "parameters": "(Throwable e)", "modifiers": "public static", "return": "RuntimeException", "signature": "RuntimeException rethrow(Throwable e)", "full_signature": "public static RuntimeException rethrow(Throwable e)", "class_method_signature": "ExceptionExt.rethrow(Throwable e)", "testcase": false, "constructor": false}, {"identifier": "rethrow", "parameters": "(Callable<T> func)", "modifiers": "public static", "return": "T", "signature": "T rethrow(Callable<T> func)", "full_signature": "public static T rethrow(Callable<T> func)", "class_method_signature": "ExceptionExt.rethrow(Callable<T> func)", "testcase": false, "constructor": false}, {"identifier": "rethrow", "parameters": "(RunnableWithExceptions func)", "modifiers": "public static", "return": "void", "signature": "void rethrow(RunnableWithExceptions func)", "full_signature": "public static void rethrow(RunnableWithExceptions func)", "class_method_signature": "ExceptionExt.rethrow(RunnableWithExceptions func)", "testcase": false, "constructor": false}, {"identifier": "rethrow", "parameters": "(RunnableWithExceptions func, Consumer<Throwable> onErrorHandler)", "modifiers": "public static", "return": "void", "signature": "void rethrow(RunnableWithExceptions func, Consumer<Throwable> onErrorHandler)", "full_signature": "public static void rethrow(RunnableWithExceptions func, Consumer<Throwable> onErrorHandler)", "class_method_signature": "ExceptionExt.rethrow(RunnableWithExceptions func, Consumer<Throwable> onErrorHandler)", "testcase": false, "constructor": false}, {"identifier": "doTry", "parameters": "(Supplier<T> callable)", "modifiers": "public static", "return": "Optional<T>", "signature": "Optional<T> doTry(Supplier<T> callable)", "full_signature": "public static Optional<T> doTry(Supplier<T> callable)", "class_method_signature": "ExceptionExt.doTry(Supplier<T> callable)", "testcase": false, "constructor": false}, {"identifier": "toMessage", "parameters": "(Throwable error)", "modifiers": "public static", "return": "String", "signature": "String toMessage(Throwable error)", "full_signature": "public static String toMessage(Throwable error)", "class_method_signature": "ExceptionExt.toMessage(Throwable error)", "testcase": false, "constructor": false}, {"identifier": "toMessageChain", "parameters": "(Throwable error)", "modifiers": "public static", "return": "String", "signature": "String toMessageChain(Throwable error)", "full_signature": "public static String toMessageChain(Throwable error)", "class_method_signature": "ExceptionExt.toMessageChain(Throwable error)", "testcase": false, "constructor": false}, {"identifier": "unpackRuntimeException", "parameters": "(Throwable exception)", "modifiers": "public static", "return": "Throwable", "signature": "Throwable unpackRuntimeException(Throwable exception)", "full_signature": "public static Throwable unpackRuntimeException(Throwable exception)", "class_method_signature": "ExceptionExt.unpackRuntimeException(Throwable exception)", "testcase": false, "constructor": false}], "file": "titus-common/src/main/java/com/netflix/titus/common/util/ExceptionExt.java"}, "focal_method": {"identifier": "toMessageChain", "parameters": "(Throwable error)", "modifiers": "public static", "return": "String", "body": "public static String toMessageChain(Throwable error) {\n        StringBuilder sb = new StringBuilder();\n        Throwable current = error;\n        while (current != null) {\n            String message = current.getMessage() != null ? current.getMessage() : \"<no_message>\";\n            sb.append('(').append(current.getClass().getSimpleName()).append(')').append(' ').append(message);\n            if (current.getCause() != null) {\n                sb.append(\" -CAUSED BY-> \");\n            }\n            current = current.getCause();\n        }\n        return sb.toString();\n    }", "signature": "String toMessageChain(Throwable error)", "full_signature": "public static String toMessageChain(Throwable error)", "class_method_signature": "ExceptionExt.toMessageChain(Throwable error)", "testcase": false, "constructor": false, "invocations": ["getMessage", "getMessage", "append", "append", "append", "append", "append", "getSimpleName", "getClass", "getCause", "append", "getCause", "toString"]}, "repository": {"repo_id": 107330274, "url": "https://github.com/Netflix/titus-control-plane", "stars": 241, "created": "10/17/2017 10:20:55 PM +00:00", "updates": "2020-01-25T13:01:05+00:00", "fork": "False", "license": "licensed"}}